import { useMemo, useState } from 'react'
import { categories, demoTorrents, initialPlugins, type Category, type Plugin, type Torrent, type View } from './data'
import { DemoDiscoveryProvider, PluginRegistry } from './services'

const nav: { id: View; label: string; icon: string }[] = [
  { id: 'discover', label: 'Discover', icon: '✦' }, { id: 'search', label: 'Search', icon: '⌕' }, { id: 'downloads', label: 'Downloads', icon: '↓' }, { id: 'library', label: 'Library', icon: '▣' }, { id: 'plugins', label: 'Plugins', icon: '⌘' }, { id: 'settings', label: 'Settings', icon: '⚙' }
]

export default function App() {
  const [view, setView] = useState<View>('discover'); const [dark, setDark] = useState(true); const [query, setQuery] = useState(''); const [category, setCategory] = useState<Category>('All'); const [selected, setSelected] = useState<Torrent | null>(null); const [plugins, setPlugins] = useState<Plugin[]>(initialPlugins); const [downloads, setDownloads] = useState<Torrent[]>([])
  const registry = useMemo(() => { const r = new PluginRegistry(); r.register(new DemoDiscoveryProvider(demoTorrents)); return r }, [])
  const filtered = useMemo(() => demoTorrents.filter(t => (category === 'All' || t.category === category) && (!query || `${t.title} ${t.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase()))), [category, query])
  const startDownload = (torrent: Torrent) => { if (!downloads.find(d => d.id === torrent.id)) setDownloads([...downloads, torrent]); setSelected(null); setView('downloads') }
  const togglePlugin = (id: string) => setPlugins(plugins.map(p => p.id === id ? { ...p, enabled: !p.enabled } : p))

  return <div className={dark ? 'app dark' : 'app'}>
    <aside className="sidebar"><div className="brand" onClick={() => setView('discover')}><span className="brand-mark">✦</span><span>Torrent<span>Nova</span></span></div><div className="workspace-label">WORKSPACE</div><nav>{nav.map(item => <button key={item.id} className={view === item.id ? 'nav-item active' : 'nav-item'} onClick={() => setView(item.id)}><b>{item.icon}</b>{item.label}{item.id === 'downloads' && downloads.length > 0 && <em>{downloads.length}</em>}</button>)}</nav><div className="sidebar-bottom"><div className="connection"><span className="pulse" /> Demo mode <small>Local catalog</small></div><button className="user-card"><span className="avatar">K</span><span><strong>Local workspace</strong><small>Personal library</small></span><b>•••</b></button></div></aside>
    <main className="main"><header><button className="mobile-brand" onClick={() => setView('discover')}>✦ Nova</button><div className="breadcrumbs"><span>Workspace</span><b>/</b><strong>{nav.find(n => n.id === view)?.label}</strong></div><div className="header-actions"><button className="icon-button" onClick={() => setDark(!dark)} title="Toggle theme">{dark ? '☼' : '☾'}</button><button className="help">?</button></div></header>
      <div className="content">{view === 'discover' && <Discover setView={setView} setCategory={setCategory} query={query} setQuery={setQuery} setSelected={setSelected} startDownload={startDownload} filtered={filtered} />}{view === 'search' && <Search query={query} setQuery={setQuery} category={category} setCategory={setCategory} setSelected={setSelected} startDownload={startDownload} filtered={filtered} registry={registry} />}{view === 'downloads' && <Downloads downloads={downloads} setSelected={setSelected} />}{view === 'library' && <Library downloads={downloads} setSelected={setSelected} />}{view === 'plugins' && <Plugins plugins={plugins} togglePlugin={togglePlugin} />}{view === 'settings' && <Settings dark={dark} setDark={setDark} />}</div>
    </main>{selected && <Details torrent={selected} close={() => setSelected(null)} startDownload={startDownload} />}
  </div>
}

type CardProps = { torrent: Torrent; setSelected: (t: Torrent) => void; startDownload: (t: Torrent) => void }
function TorrentCard({ torrent, setSelected, startDownload }: CardProps) { return <article className="torrent-card"><div className="card-top"><span className={`cover ${torrent.category.toLowerCase()}`}>{torrent.category === 'Movies' ? '◉' : torrent.category === 'Music' ? '♫' : torrent.category === 'Books' ? '▤' : '✦'}</span><span className="category">{torrent.category}</span><span className="verified">{torrent.verified ? '✓ Verified' : 'Demo'}</span></div><h3 onClick={() => setSelected(torrent)}>{torrent.title}</h3><div className="stats"><span>↓ {torrent.size}</span><span className="seed">▲ {torrent.seeders}</span><span className="leech">▼ {torrent.leechers}</span></div><div className="card-foot"><span>{torrent.provider} · {torrent.age}</span><button onClick={() => startDownload(torrent)}>Add to downloads</button></div></article> }
function PageTitle({ eyebrow, title, children }: { eyebrow: string; title: string; children?: React.ReactNode }) { return <div className="page-title"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1></div>{children}</div> }
function Discover({ setView, setCategory, query, setQuery, setSelected, startDownload, filtered }: any) { return <><PageTitle eyebrow="THURSDAY · SEPTEMBER 17" title="Good evening, explorer."><button className="primary" onClick={() => setView('search')}>⌕ Search catalog</button></PageTitle><section className="hero"><div><span className="hero-kicker">DISCOVERY CENTER</span><h2>Find your next <i>favorite.</i></h2><p>Explore a curated demo catalog built for a faster, calmer way to discover content.</p><div className="hero-search"><span>⌕</span><input value={query} onChange={e => { setQuery(e.target.value); setView('search') }} placeholder="Search titles, creators, or tags..." /><kbd>⌘ K</kbd></div></div><div className="orbit"><span>✦</span><span>◌</span><span>✧</span></div></section><div className="section-head"><div><h2>Trending now</h2><p>Fresh demo releases from your enabled providers.</p></div><button className="text-button" onClick={() => setView('search')}>View all →</button></div><div className="chips">{categories.map(c => <button className={c === 'All' ? 'chip selected' : 'chip'} onClick={() => setCategory(c)} key={c}>{c}</button>)}</div><div className="card-grid">{filtered.slice(0, 4).map((t: Torrent) => <TorrentCard key={t.id} torrent={t} setSelected={setSelected} startDownload={startDownload} />)}</div></> }
function Search({ query, setQuery, category, setCategory, setSelected, startDownload, filtered, registry }: any) { return <><PageTitle eyebrow="DISCOVERY" title="Search catalog"><span className="result-count">{filtered.length} results</span></PageTitle><div className="large-search"><span>⌕</span><input autoFocus value={query} onChange={e => setQuery(e.target.value)} placeholder="Try “aurora”, “music”, or “open license”" /><button onClick={() => setQuery('')}>Clear</button></div><div className="results-toolbar"><div className="chips">{categories.map(c => <button className={c === category ? 'chip selected' : 'chip'} onClick={() => setCategory(c)} key={c}>{c}</button>)}</div><span className="provider-note">Using {registry.list().length} demo provider · Safe offline data</span></div><div className="result-list">{filtered.map((t: Torrent) => <TorrentCard key={t.id} torrent={t} setSelected={setSelected} startDownload={startDownload} />)}{filtered.length === 0 && <div className="empty"><span>⌕</span><h3>No results yet</h3><p>Try another phrase or select All categories.</p></div>}</div></> }
function Downloads({ downloads, setSelected }: any) { return <><PageTitle eyebrow="YOUR ACTIVITY" title="Downloads"><span className="result-count">{downloads.length} active</span></PageTitle>{downloads.length ? <div className="download-list">{downloads.map((t: Torrent, i: number) => <div className="download-row" key={t.id}><span className="download-icon">↓</span><div><strong>{t.title}</strong><small>{t.size} · Demo queue</small></div><div className="progress"><span style={{ width: `${42 + i * 17}%` }} /></div><b>{42 + i * 17}%</b><button onClick={() => setSelected(t)}>Details</button></div>)}</div> : <div className="empty"><span>↓</span><h3>Your queue is clear</h3><p>Add a result from Discover or Search to see it here.</p></div>}</> }
function Library({ downloads, setSelected }: any) { return <><PageTitle eyebrow="YOUR COLLECTION" title="Library"><button className="secondary">+ Create collection</button></PageTitle><div className="library-banner"><span>▣</span><div><strong>Keep your discoveries close.</strong><p>Saved content and collections will appear here. Downloads are automatically remembered.</p></div></div><div className="section-head"><div><h2>Recently added</h2></div></div><div className="card-grid">{downloads.map((t: Torrent) => <TorrentCard key={t.id} torrent={t} setSelected={setSelected} startDownload={() => {}} />)}</div>{!downloads.length && <div className="empty compact"><h3>No saved items</h3><p>Build your library from the Discovery Center.</p></div>}</> }
function Plugins({ plugins, togglePlugin }: any) { return <><PageTitle eyebrow="EXTEND NOVA" title="Plugin Manager"><button className="primary">+ Browse providers</button></PageTitle><div className="notice"><span>✦</span><p><strong>Provider safety first.</strong> TorrentNova only ships with offline demo data. Review and explicitly authorize any provider you add later.</p></div><div className="plugin-list">{plugins.map((p: Plugin) => <div className="plugin-row" key={p.id}><span className="plugin-logo">{p.name[0]}</span><div className="plugin-copy"><strong>{p.name} <small>v{p.version}</small></strong><p>{p.description}</p><em>{p.kind}</em></div><button className={p.enabled ? 'toggle on' : 'toggle'} onClick={() => togglePlugin(p.id)}><span /></button></div>)}</div></> }
function Settings({ dark, setDark }: any) { return <><PageTitle eyebrow="PREFERENCES" title="Settings"><button className="primary">Save changes</button></PageTitle><div className="settings-grid"><section className="settings-card"><h3>Appearance</h3><p>Make Nova feel like your workspace.</p><label className="setting-row"><span><strong>Dark interface</strong><small>Use the low-light color palette.</small></span><button className={dark ? 'toggle on' : 'toggle'} onClick={() => setDark(!dark)}><span /></button></label><label className="setting-row"><span><strong>Compact cards</strong><small>Show more results per row.</small></span><button className="toggle"><span /></button></label></section><section className="settings-card"><h3>Discovery</h3><p>Control how providers contribute results.</p><label className="select-row"><span>Default category</span><select><option>All content</option><option>Movies</option><option>Series</option></select></label><label className="select-row"><span>Results per page</span><select><option>24 results</option><option>48 results</option></select></label></section></div></> }
function Details({ torrent, close, startDownload }: { torrent: Torrent; close: () => void; startDownload: (t: Torrent) => void }) { return <div className="modal-backdrop" onClick={close}><section className="details" onClick={e => e.stopPropagation()}><button className="close" onClick={close}>×</button><span className={`detail-cover cover ${torrent.category.toLowerCase()}`}>✦</span><div className="eyebrow">{torrent.category} · {torrent.provider}</div><h2>{torrent.title}</h2><p className="detail-description">{torrent.description}</p><div className="detail-stats"><span><small>SIZE</small><b>{torrent.size}</b></span><span><small>SEEDERS</small><b className="seed">{torrent.seeders}</b></span><span><small>LEECHERS</small><b>{torrent.leechers}</b></span></div><div className="tag-list">{torrent.tags.map(tag => <span key={tag}>{tag}</span>)}</div><button className="primary full" onClick={() => startDownload(torrent)}>↓ Add to downloads</button><p className="disclaimer">Demo record only. No external torrent data or network transfer is initiated.</p></section></div> }
